

name: 腾讯新闻自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 */3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TX_CK: ${{ secrets.TX_CK }}
        TX_CK2: ${{ secrets.TX_CK2 }}
        TX_CK3: ${{ secrets.TX_CK3 }}
        TX_CK4: ${{ secrets.TX_CK4 }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【腾讯新闻自动阅读账号一】'
        if: env.TX_CK
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK }}
          TX_READ: ${{ secrets.TX_READ }}
          TX_VIDEO: ${{ secrets.TX_VIDEO }}
          
      - name: '运行 【腾讯新闻自动阅读账号二】'
        if: env.TX_CK2
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK2 }}
          TX_READ: ${{ secrets.TX_READ2 }}
          TX_VIDEO: ${{ secrets.TX_VIDEO2 }}
       
      - name: '运行 【腾讯新闻自动阅读账号三】'
        if: env.TX_CK3
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK3 }}
          TX_READ: ${{ secrets.TX_READ3 }}
          TX_VIDEO: ${{ secrets.TX_VIDEO3 }}
   
      - name: '运行 【腾讯新闻自动阅读账号四】'
        if: env.TX_CK4
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK4 }}
          TX_READ: ${{ secrets.TX_READ4 }}
          TX_VIDEO: ${{ secrets.TX_VIDEO4 }}
